#!/bin/sh

cd tmp/

config_h="config.h"

getheader() {
name=$(basename $1)
cat << EOF >> $name.c
#include <$1>

int main() {return 0;}
EOF
 
$CC -E $name.c > /dev/null 

if test $? = "0"; then 
	echo "#define $2 1" >> $config_h
fi
}

getdefined() {
name=$(basename $1)
for h in $headers; do
	echo "#include <$1>" >> $name.c
done
cat << EOF >> $name.c

int main() {
if ($1) {
return 0;
}
else {
return 1; 
}
}
EOF
 
$CC -E $name.c > /dev/null 

if test $? = "0"; then 
	echo "#define $2 1" >> $config_h
fi

}

getheader assert.h HAVE_ASSERT_H
getheader dirent.h HAVE_DIRENT_H
getheader dlfcn.h  HAVE_DLFCN_H
getheader errno.h  HAVE_ERRNO_H
getheader fcntl.h  HAVE_FCNTL_H
getheader inttypes.h HAVE_INTTYPES_H
getheader libintl.h HAVE_LIBINTL_H
getheader limits.h HAVE_LIMITS_H
getheader malloc.h HAVE_MALLOC_H
getheader stdint.h HAVE_STDINT_H
getheader stdio.h  HAVE_STDIO_H
getheader stdlib.h HAVE_STDLIB_H
getheader strings.h HAVE_STRINGS_H
getheader string.h HAVE_STRING_H
getheader sys/param.h HAVE_SYS_PARAM_H
getheader sys/stat.h HAVE_SYS_STAT_H
getheader sys/types.h HAVE_SYS_TYPES_H
getheader unistd.h HAVE_UNISTD_H
getheader wchar.h HAVE_WCHAR_H
getheader minix/config.h HAVE_MINIX_CONFIG_H
getheader alloca.h HAVE_ALLOCA_H

getdefined alloca HAVE_ALLOCA
getdefined asprintf HAVE_ASPRINTF
getdefined flockfile HAVE_FLOCKFILE
getdefined fputs_unlocked HAVE_FPUTS_UNLOCKED
getdefined fwrite_unlocked HAVE_FWRITE_UNLOCKED
getdefined memcpy HAVE_MEMCPY
getdefined strdup HAVE_STRDUP 
getdefined strerror HAVE_STRERROR
getdefined strndup HAVE_STRNDUP
getdefined vprintf HAVE_VPRINTF
